#!/usr/bin/env python3

import sys

from singularity.container import Container

"""
Wrapper for Container.build() call
"""

def main():
    container = Container()
    container.run(sys.argv[1:])

if __name__ == "__main__":
    main()
