#!/usr/bin/env python3

# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

import sys

from singularity.container import Container

"""
Wrapper for Container.build() call
"""

def main():
    container = Container()
    container.pull()

if __name__ == "__main__":
    main()
