# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

"""
Tests for the TT 64-entry PMA scheme in Loader.setup_pma():

- pmacfg0-15 written directly (0x7E0-0x7EF), each paired with a pmamask clear (0x7F0-0x7FF)
- pmacfg/pmamask 16-63 written indirectly via miselect/mireg/mireg2
- catchalls re-established at entries 62 (IO) and 63 (DRAM)
- FeatMgr.num_pmas defaults to 64

This file is private (excluded from public release via .tafconfig).
"""

import re
import unittest
from typing import Optional

from riescue.dtest_framework.config import FeatMgr
from riescue.dtest_framework.pool import Pool
from riescue.dtest_framework.runtime import Runtime
from riescue.dtest_framework.runtime.loader import Loader, PMA_INDIRECT_SELECT_BASE, PMA_IO_CATCHALL, PMA_DRAM_CATCHALL
from riescue.lib.rand import RandNum


def make_loader(num_regions: int, num_pmas: Optional[int] = None) -> Loader:
    """Build a Loader with needs_pma set and ``num_regions`` non-adjacent memory PMA regions."""
    featmgr = FeatMgr(needs_pma=True)
    if num_pmas is not None:
        featmgr.num_pmas = num_pmas
    pool = Pool()
    for i in range(num_regions):
        # Space regions 2 pages apart so consolidation cannot merge them
        pool.pma_regions.add_region(0x8000_0000 + i * 0x2000, 0x1000, "memory")
    runtime = Runtime(rng=RandNum(seed=42), pool=pool, featmgr=featmgr)
    loader = runtime._modules["loader"]
    assert isinstance(loader, Loader)
    return loader


class LoaderPmaTest(unittest.TestCase):
    """Check the assembly generated by Loader.setup_pma()."""

    def test_num_pmas_default_is_64(self):
        self.assertEqual(FeatMgr().num_pmas, 64)

    def test_empty_pma_regions_generates_nothing(self):
        """No PMA regions -> no setup code, no catchall writes."""
        code = make_loader(0).setup_pma()
        self.assertEqual(code, "")

    def test_direct_entries_write_pmacfg_and_clear_pmamask(self):
        """Entries 0-15 use direct CSRs: pmacfg @ 0x7E0+i, pmamask cleared @ 0x7F0+i."""
        n = 16
        code = make_loader(n).setup_pma()
        for i in range(n):
            self.assertIn(f"csrw 0x{0x7E0 + i:x}, t0", code, f"missing pmacfg{i} write")
            self.assertIn(f"csrw 0x{0x7F0 + i:x}, x0", code, f"missing pmamask{i} clear")
        # No indirect writes except the two catchall entries
        selects = re.findall(r"li t1, (0x8[0-9a-f]+)", code)
        self.assertEqual(selects, [f"0x{PMA_INDIRECT_SELECT_BASE + 62:x}", f"0x{PMA_INDIRECT_SELECT_BASE + 63:x}"])

    def test_indirect_entries_use_miselect_mireg_mireg2(self):
        """Entries 16+ have no direct CSRs; they go through miselect/mireg/mireg2."""
        n = 20
        code = make_loader(n).setup_pma()
        for i in range(16, n):
            self.assertIn(f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + i:x}", code, f"missing miselect value for entry {i}")
        # Exactly 16 direct pmacfg writes (0x7E0-0x7EF); entries 16+ must not spill into 0x7F0+
        direct_pmacfg_writes = re.findall(r"csrw (0x7[ef][0-9a-f]), t0", code)
        self.assertEqual(direct_pmacfg_writes, [f"0x{0x7E0 + i:x}" for i in range(16)])
        # Exactly 16 direct pmamask clears (0x7F0-0x7FF)
        direct_pmamask_clears = re.findall(r"csrw (0x7f[0-9a-f]), x0", code)
        self.assertEqual(direct_pmamask_clears, [f"0x{0x7F0 + i:x}" for i in range(16)])
        # Entry 16 maps to miselect 0x8000000000000010 per spec
        self.assertIn("li t1, 0x8000000000000010", code)
        # Every indirect pmacfg write pairs a mireg write with a mireg2 clear
        self.assertEqual(len(re.findall(r"csrw miselect, t1", code)), (n - 16) + 2)  # +2 catchalls
        self.assertEqual(len(re.findall(r"csrw mireg, t0", code)), (n - 16) + 2)
        self.assertEqual(len(re.findall(r"csrw mireg2, x0", code)), (n - 16) + 2)

    def test_catchalls_at_62_and_63(self):
        """IO catchall lands on entry 62, DRAM catchall on entry 63, with pmamask cleared."""
        code = make_loader(1).setup_pma()
        io_select = f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 62:x}"
        dram_select = f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 63:x}"
        self.assertIn(io_select, code)
        self.assertIn(dram_select, code)
        self.assertIn(f"li t0, 0x{PMA_IO_CATCHALL:x}", code)
        self.assertIn(f"li t0, 0x{PMA_DRAM_CATCHALL:x}", code)
        # Catchall values match the pmacfg14/15 boot resets in whisper_config.json
        self.assertEqual(PMA_IO_CATCHALL, 0x7C00000000000007)
        self.assertEqual(PMA_DRAM_CATCHALL, 0xE0000000000001E7)
        # IO catchall (lower entry, higher priority) must be written before DRAM
        self.assertLess(code.index(io_select), code.index(dram_select))
        # mireg2 cleared for both catchall entries
        self.assertEqual(len(re.findall(r"csrw mireg2, x0", code)), 2)

    def test_select_value_bounds(self):
        """Reg 16 -> 0x8000000000000010, reg 63 -> 0x800000000000003F per spec."""
        self.assertEqual(PMA_INDIRECT_SELECT_BASE + 16, 0x8000000000000010)
        self.assertEqual(PMA_INDIRECT_SELECT_BASE + 63, 0x800000000000003F)

    def test_max_entries_accepted(self):
        """64 regions fit in num_pmas=64 (entries 62/63 then overwritten by catchalls)."""
        code = make_loader(64).setup_pma()
        self.assertIn(f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 63:x}", code)

    def test_too_many_regions_raises(self):
        """More regions than num_pmas must raise."""
        with self.assertRaises(ValueError):
            make_loader(65).setup_pma()

    def test_num_pmas_16_still_caps(self):
        """Explicit --num_pmas 16 keeps the old capacity check."""
        with self.assertRaises(ValueError):
            make_loader(17, num_pmas=16).setup_pma()


if __name__ == "__main__":
    unittest.main()
