# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

"""
Tests for the TT 64-entry PMA scheme in Loader.setup_pma():

- pmacfg0-15 written directly (0x7E0-0x7EF), each paired with a pmamask clear (0x7F0-0x7FF)
- pmacfg/pmamask 16-63 written indirectly via miselect/mireg/mireg2
- catchalls re-established at entries 62 (IO) and 63 (DRAM)
- FeatMgr.num_pmas defaults to 64

This file is private (excluded from public release via .tafconfig).
"""

import re
import unittest
from typing import Optional

from riescue.dtest_framework.config import FeatMgr
from riescue.dtest_framework.lib.pma import PmaInfo
from riescue.dtest_framework.pool import Pool
from riescue.dtest_framework.runtime import Runtime
from riescue.dtest_framework.runtime.loader import Loader, PMA_INDIRECT_SELECT_BASE, PMA_IO_CATCHALL, PMA_DRAM_CATCHALL
from riescue.lib.rand import RandNum


def make_loader(num_regions: int, num_pmas: Optional[int] = None, user_programmable: int = 0, num_carveouts: int = 0, carveouts: tuple = (), indirect_pct: Optional[int] = None) -> Loader:
    """Build a Loader with needs_pma set and ``num_regions`` non-adjacent memory PMA regions."""
    featmgr = FeatMgr(needs_pma=True, user_programmable_pmacfg=user_programmable)
    if num_pmas is not None:
        featmgr.num_pmas = num_pmas
    if indirect_pct is not None:
        featmgr.pma_indirect_access_pct = indirect_pct
    pool = Pool()
    for i in range(num_regions):
        # Space regions 2 pages apart so consolidation cannot merge them
        pool.pma_regions.add_region(0x8000_0000 + i * 0x2000, 0x1000, "memory")
    # Explicit (base, size) carve-outs when placement matters, otherwise a disjoint 0x9000_0000 run
    spans = carveouts if carveouts else tuple((0x9000_0000 + j * 0x2000, 0x1000) for j in range(num_carveouts))
    for j, (base, size) in enumerate(spans):
        pool.pma_regions.add_entry(
            PmaInfo(
                pma_name=f"pma_carve_{j}",
                pma_address=base,
                pma_size=size,
                pma_memory_type="memory",
                pma_cacheability="noncacheable",
                pma_amo_type="none",
                pma_routing_to="noncoherent",
                pma_valid=True,
            )
        )
    runtime = Runtime(rng=RandNum(seed=42), pool=pool, featmgr=featmgr)
    loader = runtime._modules["loader"]
    assert isinstance(loader, Loader)
    return loader


def make_random_loader(
    num_regions: int = 2,
    num_random: int = 3,
    user_programmable: int = 0,
    num_pmas: Optional[int] = None,
    masked_indices: tuple = (),
    num_carveouts: int = 0,
    indirect_pct: int = 0,
) -> Loader:
    """Build a Loader with PMA randomization enabled, defined regions, carve-outs, and decoys."""
    featmgr = FeatMgr(needs_pma=True, enable_pma_randomization=True, user_programmable_pmacfg=user_programmable, pma_indirect_access_pct=indirect_pct)
    if num_pmas is not None:
        featmgr.num_pmas = num_pmas
    pool = Pool()
    for i in range(num_regions):
        pool.pma_regions.add_region(0x8000_0000 + i * 0x2000, 0x1000, "memory")
    for j in range(num_carveouts):
        pool.pma_regions.add_entry(
            PmaInfo(
                pma_name=f"pma_carve_{j}",
                pma_address=0x9000_0000 + j * 0x2000,
                pma_size=0x1000,
                pma_memory_type="io",
                pma_read=True,
                pma_write=False,
                pma_execute=False,
                pma_amo_type="none",
                pma_routing_to="noncoherent",
                pma_valid=True,
            )
        )
    for k in range(num_random):
        pool.pma_random_regions.append(
            PmaInfo(
                pma_name=f"pma_rand_{k}",
                pma_address=0x2000_0000 + k * 0x10000,
                pma_size=0x1000,
                pma_mask=(1 << 20) if k in masked_indices else 0,
                pma_memory_type="memory",
                pma_cacheability="noncacheable",
                pma_amo_type="none",
                pma_valid=True,
                pma_randomized=True,
            )
        )
    runtime = Runtime(rng=RandNum(seed=42), pool=pool, featmgr=featmgr)
    loader = runtime._modules["loader"]
    assert isinstance(loader, Loader)
    return loader


def entry_indices(code: str) -> list:
    """List programmed pmacfg entry indices from the emitted comments."""
    return [int(idx) for idx in re.findall(r"# Setting up pmacfg(\d+)", code)]


def invalidated_indices(code: str) -> list:
    """List pmacfg entry indices cleared by the invalidation band."""
    return [int(idx) for idx in re.findall(r"# Invalidate pmacfg(\d+)", code)]


class LoaderPmaTest(unittest.TestCase):
    """Check the assembly generated by Loader.setup_pma()."""

    def entry_indices(self, code: str) -> list:
        return entry_indices(code)

    def test_num_pmas_default_is_64(self):
        self.assertEqual(FeatMgr().num_pmas, 64)

    def test_non_randomize_capacity_includes_reserved_and_catchalls(self):
        """reserved + regions + catchalls must fit num_pmas; overflow raises instead of clobbering entries."""
        with self.assertRaises(ValueError):
            make_loader(3, num_pmas=16, user_programmable=15).setup_pma()
        code = make_loader(3, num_pmas=16, user_programmable=11).setup_pma()
        self.assertIn("# Setting up pmacfg13 ", code)  # regions at 11..13, catchalls at 14/15
        self.assertIn("# PMA catchall pmacfg14", code)

    def test_empty_pma_regions_generates_nothing(self):
        """No PMA regions -> no setup code, no catchall writes."""
        code = make_loader(0).setup_pma()
        self.assertEqual(code, "")

    def test_direct_entries_write_pmacfg_and_clear_pmamask(self):
        """Carve-outs claim entries 0-15 and use direct CSRs: pmacfg @ 0x7E0+i, pmamask cleared @ 0x7F0+i."""
        n = 16
        code = make_loader(1, num_carveouts=n).setup_pma()
        for i in range(n):
            self.assertIn(f"csrw 0x{0x7E0 + i:x}, t0", code, f"missing pmacfg{i} write")
            self.assertIn(f"csrw 0x{0x7F0 + i:x}, x0", code, f"missing pmamask{i} clear")
        # The carve-out band fills the direct CSRs, so nothing else may touch 0x7E0-0x7EF
        self.assertEqual(re.findall(r"csrw (0x7[ef][0-9a-f]), t0", code), [f"0x{0x7E0 + i:x}" for i in range(n)])
        self.assertEqual(re.findall(r"csrw (0x7f[0-9a-f]), x0", code), [f"0x{0x7F0 + i:x}" for i in range(n)])
        # The catchalls are established before any entry below them changes
        selects = re.findall(r"li t1, (0x8[0-9a-f]+)", code)
        self.assertEqual(selects[:2], [f"0x{PMA_INDIRECT_SELECT_BASE + 62:x}", f"0x{PMA_INDIRECT_SELECT_BASE + 63:x}"])

    def test_indirect_entries_use_miselect_mireg_mireg2(self):
        """Memory-map entries land above 16, so they go through miselect/mireg/mireg2."""
        n = 4
        code = make_loader(n).setup_pma()
        for i in range(62 - n, 62):
            self.assertIn(f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + i:x}", code, f"missing miselect value for entry {i}")
            self.assertIn(f"# Setting up pmacfg{i} (indirect", code)
        # Nothing is programmed through the direct CSRs: the low band holds no carve-outs here
        self.assertEqual(re.findall(r"csrw (0x7[ef][0-9a-f]), t0", code), [])
        # Entry 16 maps to miselect 0x8000000000000010 per spec
        self.assertEqual(PMA_INDIRECT_SELECT_BASE + 16, 0x8000000000000010)
        # Every indirect pmacfg write pairs a mireg write with a mireg2 clear
        self.assertEqual(len(re.findall(r"csrw mireg, t0", code)), n + 2)  # +2 catchalls
        self.assertEqual(len(re.findall(r"csrw mireg2, x0", code)), n + len(re.findall(r"csrw mireg, x0", code)))

    def test_catchalls_at_62_and_63(self):
        """IO catchall lands on entry 62, DRAM catchall on entry 63, and both are written first."""
        code = make_loader(1).setup_pma()
        io_select = f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 62:x}"
        dram_select = f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 63:x}"
        self.assertIn(io_select, code)
        self.assertIn(dram_select, code)
        self.assertIn(f"li t0, 0x{PMA_IO_CATCHALL:x}", code)
        self.assertIn(f"li t0, 0x{PMA_DRAM_CATCHALL:x}", code)
        # Catchall values match the pmacfg14/15 boot resets in whisper_config.json
        self.assertEqual(PMA_IO_CATCHALL, 0x7C00000000000007)
        self.assertEqual(PMA_DRAM_CATCHALL, 0xE0000000000001E7)
        # IO catchall (lower entry, higher priority) must be written before DRAM
        self.assertLess(code.index(io_select), code.index(dram_select))
        # Catchalls precede every programmed entry: coverage must not lapse while the band is invalidated
        self.assertLess(code.index(dram_select), code.index("# Setting up pmacfg61"))
        # No pmamask write on the catchall entries; that flips whisper to masked-compare (see _setup_pma_catchall)
        catchall_block = code[code.index(io_select) : code.index("# Setting up pmacfg61")]
        self.assertNotIn("mireg2", catchall_block)

    def test_select_value_bounds(self):
        """Reg 16 -> 0x8000000000000010, reg 63 -> 0x800000000000003F per spec."""
        self.assertEqual(PMA_INDIRECT_SELECT_BASE + 16, 0x8000000000000010)
        self.assertEqual(PMA_INDIRECT_SELECT_BASE + 63, 0x800000000000003F)

    def test_max_entries_accepted(self):
        """62 regions + 2 catchalls exactly fill num_pmas=64."""
        code = make_loader(62).setup_pma()
        self.assertIn("# Setting up pmacfg61 ", code)
        self.assertIn(f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 63:x}", code)

    def test_too_many_regions_raises(self):
        """Regions that leave no room for the catchalls must raise."""
        with self.assertRaises(ValueError):
            make_loader(63).setup_pma()

    def test_num_pmas_16_still_caps(self):
        """Explicit --num_pmas 16 keeps the old capacity check."""
        with self.assertRaises(ValueError):
            make_loader(17, num_pmas=16).setup_pma()

    def test_no_randomization_artifacts(self):
        """Flag off: decoys and randomized pmamask values stay out of the emitted code."""
        code = make_loader(3, num_carveouts=1).setup_pma()
        self.assertNotIn("Set pmamask", code)
        self.assertNotIn("pma_rand", code)

    def test_layout_carveouts_low_memmap_under_catchalls(self):
        """Carve-outs take the lowest entries; the memory map packs directly under the catchalls."""
        code = make_loader(3, num_carveouts=2).setup_pma()
        self.assertEqual(self.entry_indices(code), [0, 1, 59, 60, 61])
        for i in (0, 1):
            self.assertIn(f"# Setting up pmacfg{i} for name=pma_carve_", code)
        for i in (59, 60, 61):
            self.assertNotIn("name=pma_carve_", code.split(f"# Setting up pmacfg{i} ")[1].split("\n")[0])

    def test_carveout_outranks_containing_memmap_region(self):
        """A carve-out inside a map region is legal and gets the lower (winning) entry."""
        loader = make_loader(0, carveouts=((0x8000_4000, 0x1000),))
        loader.pool.pma_regions.add_region(0x8000_0000, 0x10_0000, "memory")
        code = loader.setup_pma()
        self.assertEqual(self.entry_indices(code), [0, 61])
        self.assertIn("# Setting up pmacfg0 for name=pma_carve_0", code)

    def test_carveout_values_are_programmed_not_zero(self):
        """Flag off must force the encoder: the legacy path emits pmacfg=0 for pma_valid carve-outs."""
        code = make_loader(1, num_carveouts=1).setup_pma()
        carveout_block = code.split("# Setting up pmacfg0 ")[1]
        value = re.search(r"li t0, (0x[0-9a-f]+)", carveout_block)
        assert value is not None
        self.assertNotEqual(int(value.group(1), 16), 0, "carve-out must be programmed with a real pmacfg value")

    def test_band_between_groups_invalidated(self):
        """Entries between the carve-outs and the memory map are cleared so boot 14/15 stop shadowing."""
        code = make_loader(2, num_carveouts=1).setup_pma()
        # carve-out at 0, memory map at 60/61 -> invalidate exactly [1, 60)
        self.assertEqual(invalidated_indices(code), list(range(1, 60)))
        self.assertIn("# Invalidate pmacfg14", code)  # the boot catchall shadows specifically
        self.assertIn("# Invalidate pmacfg15", code)

    def test_reserved_entries_untouched(self):
        """user_programmable_pmacfg entries are neither programmed nor invalidated."""
        code = make_loader(2, user_programmable=4, num_carveouts=1).setup_pma()
        self.assertEqual(self.entry_indices(code)[0], 4)
        self.assertEqual(invalidated_indices(code), list(range(5, 60)))
        for i in range(4):
            self.assertNotIn(f"csrw 0x{0x7E0 + i:x}, ", code)

    def test_partial_straddle_raises(self):
        """A carve-out half inside a map region has no priority resolution; reject it."""
        loader = make_loader(0, carveouts=((0x7FFF_F000, 0x2000),))
        loader.pool.pma_regions.add_region(0x8000_0000, 0x10_0000, "memory")
        with self.assertRaises(ValueError) as ctx:
            loader.setup_pma()
        self.assertIn("partially overlaps", str(ctx.exception))
        self.assertIn("pma_carve_0", str(ctx.exception))

    def test_disjoint_carveout_accepted(self):
        """A carve-out outside every map region is fine (the case that escapes the check by address)."""
        loader = make_loader(0, carveouts=((0xC7C9_46EE_8A000, 0x1000),))
        loader.pool.pma_regions.add_region(0x8000_0000, 0x10_0000, "memory")
        code = loader.setup_pma()
        self.assertEqual(self.entry_indices(code), [0, 61])

    def test_indirect_pct_100_legacy_low_entries_indirect(self):
        """pct applies without randomization too: entries 0-15 programmed via miselect/mireg/mireg2."""
        code = make_loader(3, indirect_pct=100).setup_pma()
        for i in range(3):
            self.assertIn(f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + i:x}", code, f"entry {i} must use indirect access")
            self.assertNotIn(f"csrw 0x{0x7E0 + i:x},", code, f"entry {i} must not use direct pmacfg CSR")

    def test_indirect_pct_unset_legacy_stays_direct(self):
        """Unset pct auto-resolves to 0 without randomization: identical to explicit 0."""
        self.assertEqual(make_loader(3).setup_pma(), make_loader(3, indirect_pct=0).setup_pma())


class LoaderPmaRandomizationTest(unittest.TestCase):
    """Check setup_pma() layout and emission when enable_pma_randomization is on."""

    def entry_indices(self, code: str) -> list:
        """List programmed pmacfg entry indices from the emitted comments."""
        return [int(idx) for idx in re.findall(r"# Setting up pmacfg(\d+)", code)]

    def test_reserved_entries_only_zeroed(self):
        """user_programmable_pmacfg=4 shifts programming to pmacfg4+ and only ever zeroes [0..4)."""
        code = make_random_loader(num_regions=2, num_random=2, user_programmable=4).setup_pma()
        for i in range(4):
            self.assertNotIn(f"# Setting up pmacfg{i} ", code, f"reserved pmacfg{i} must hold no region")
            self.assertNotIn(f"csrw 0x{0x7E0 + i:x}, t0", code, f"reserved pmacfg{i} must never get a value")
            self.assertIn(f"# Invalidate pmacfg{i}", code, f"reserved pmacfg{i} must be zeroed at boot")
        self.assertIn("csrw 0x7e4, t0", code, "first programmed entry must be pmacfg4")

    def test_reserved_block_outranks_carveouts(self):
        """Nothing the framework programs may land below the reserved block; carve-outs come first after it."""
        code = make_random_loader(num_regions=2, num_random=2, num_carveouts=1, user_programmable=4).setup_pma()
        self.assertEqual(min(self.entry_indices(code)), 4)
        self.assertIn("# Setting up pmacfg4 ", code)
        self.assertIn("pma_carve_0", code[code.index("# Setting up pmacfg4 ") : code.index("# Setting up pmacfg5 ")])

    def test_reserved_zeroing_after_catchalls(self):
        """Reserved entries are zeroed only after the 62/63 catchalls exist, so coverage never lapses."""
        code = make_random_loader(num_regions=2, num_random=2, user_programmable=16).setup_pma()
        self.assertLess(code.index("# PMA catchall pmacfg62"), code.index("# Invalidate pmacfg0"))
        # Boot catchalls at 14/15 fall inside the reserved block here and must be cleared
        self.assertIn("csrw 0x7ee, x0", code)
        self.assertIn("csrw 0x7ef, x0", code)

    def test_layout_carveouts_then_decoys_then_memmap(self):
        """Emission order: carve-outs, randomized decoys, memory-map regions."""
        code = make_random_loader(num_regions=2, num_random=2, num_carveouts=1).setup_pma()
        positions = {name: code.index(name) for name in ("pma_carve_0", "pma_rand_0", "pma_rand_1")}
        memmap_pos = code.index("# Setting up pmacfg3 ")
        self.assertLess(positions["pma_carve_0"], positions["pma_rand_0"])
        self.assertLess(positions["pma_rand_1"], memmap_pos)

    def test_carveout_values_forced_nonzero(self):
        """pma_valid=True carve-outs must emit real pmacfg values (force bypasses the legacy quirk)."""
        code = make_random_loader(num_regions=0, num_random=0, num_carveouts=1).setup_pma()
        match = re.search(r"pma_carve_0[^\n]*\n\s+li t0, (0x[0-9a-f]+)", code)
        assert match is not None, "carve-out pmacfg write not found"
        self.assertNotEqual(int(match.group(1), 16), 0)

    def test_masked_decoy_emits_pmamask_after_pmacfg(self):
        """Masked decoys program pmamask with the mask value, strictly after the pmacfg write."""
        code = make_random_loader(num_regions=0, num_random=2, masked_indices=(1,)).setup_pma()
        self.assertIn("# Set pmamask1", code)
        self.assertIn(f"li t0, 0x{1 << 20:x}", code)
        self.assertIn("# Clear pmamask0", code)
        pmacfg_pos = code.index("# Setting up pmacfg1 ")
        pmamask_pos = code.index("# Set pmamask1")
        self.assertLess(pmacfg_pos, pmamask_pos)

    def test_masked_carveout_emits_pmamask(self):
        """Masked carve-outs (from the carve-out masking pass) program their pmamask like decoys."""
        loader = make_random_loader(num_regions=0, num_random=0, num_carveouts=1)
        carveout = loader.pool.pma_regions.consolidated_entries(merge_named=False)[0]
        assert carveout.pma_name == "pma_carve_0"
        carveout.pma_mask = 1 << 24
        code = loader.setup_pma()
        self.assertIn("# Set pmamask0", code)
        self.assertIn(f"li t0, 0x{1 << 24:x}", code)
        self.assertLess(code.index("# Setting up pmacfg0 "), code.index("# Set pmamask0"))

    def test_unused_entries_invalidated_up_to_62(self):
        """Reserved [0, 4) and unused [used, 62) are invalidated (killing boot 14/15 shadows); 62/63 are not."""
        code = make_random_loader(num_regions=2, num_random=2, user_programmable=4).setup_pma()
        used = 4 + 2 + 2
        invalidated = sorted(int(i) for i in re.findall(r"# Invalidate pmacfg(\d+)", code))
        self.assertEqual(invalidated, list(range(0, 4)) + list(range(used, 62)))
        # 62/63 hold the catchalls; they must be rewritten, never invalidated
        self.assertNotIn(62, invalidated)
        self.assertNotIn(63, invalidated)
        self.assertIn("# PMA catchall pmacfg62", code)
        self.assertIn("# PMA catchall pmacfg63", code)
        self.assertNotIn("# PMA catchall pmacfg14", code)

    def test_randomized_entries_below_16_direct_catchalls_indirect(self):
        """Entries below 16 use direct CSRs; catchalls go indirect at 62/63 like the legacy path."""
        code = make_random_loader(num_regions=2, num_random=2, user_programmable=8).setup_pma()
        self.assertEqual(sorted(self.entry_indices(code)), [8, 9, 10, 11])
        self.assertIn("csrw 0x7e8, t0", code)
        self.assertIn(f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 62:x}", code)
        self.assertIn(f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 63:x}", code)
        # Boot entries 14/15 are ordinary now: invalidated, never rewritten as catchalls
        self.assertIn("csrw 0x7ee, x0", code)
        self.assertNotIn("csrw 0x7ee, t0", code)

    def test_entries_spill_into_indirect(self):
        """Regions past entry 15 are programmed indirectly via miselect/mireg in randomize mode."""
        code = make_random_loader(num_regions=2, num_random=2, user_programmable=14).setup_pma()
        self.assertEqual(sorted(self.entry_indices(code)), [14, 15, 16, 17])
        self.assertIn("# Setting up pmacfg16 (indirect", code)
        self.assertIn("li t1, 0x8000000000000010", code)
        self.assertIn("li t1, 0x8000000000000011", code)

    def test_capacity_error_with_breakdown(self):
        """Overflow raises with the full breakdown in the message; decoys never count (they truncate)."""
        with self.assertRaises(ValueError) as ctx:
            make_random_loader(num_regions=16, num_random=8, user_programmable=47).setup_pma()
        self.assertIn("user_programmable=47", str(ctx.exception))
        self.assertIn("memory_map=16", str(ctx.exception))
        self.assertIn("> 64 PMA entries", str(ctx.exception))

    def test_decoys_truncated_to_budget(self):
        """Decoys beyond the 64-entry budget are dropped (with a warning), not fatal."""
        loader = make_random_loader(num_regions=2, num_random=8, user_programmable=56)
        with self.assertLogs("riescue.dtest_framework.runtime.loader", level="WARNING"):
            code = loader.setup_pma()
        # essential = 56 reserved + 2 memmap + 2 catchalls = 60 -> budget 4 decoys
        self.assertIn("pma_rand_3", code)
        self.assertNotIn("pma_rand_4", code)
        # Pool list is trimmed in step so addrgen exclusion matches what was actually programmed
        self.assertEqual(len(loader.pool.pma_random_regions), 4)

    def test_num_pmas_16_places_catchalls_at_14_15_direct(self):
        """Catchall entries derive from num_pmas: a 16-entry config uses direct CSRs at 14/15."""
        code = make_random_loader(num_regions=1, num_random=1, num_pmas=16).setup_pma()
        self.assertIn("# PMA catchall pmacfg14", code)
        self.assertIn("# PMA catchall pmacfg15", code)
        self.assertNotIn("# PMA catchall pmacfg62", code)
        self.assertIn("csrw 0x7ee, t0", code)  # direct catchall write, no miselect
        self.assertNotIn(f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 14:x}", code)
        invalidated = sorted(int(i) for i in re.findall(r"# Invalidate pmacfg(\d+)", code))
        self.assertEqual(invalidated, list(range(2, 14)))  # used=2 regions, up to catchall_base=14

    def test_user_programmable_above_capacity_raises(self):
        """Reserved entries that leave no room for regions plus catchalls must raise."""
        with self.assertRaises(ValueError):
            make_random_loader(num_regions=1, num_random=1, user_programmable=62).setup_pma()

    def test_catchalls_first_when_randomizing(self):
        """Catchalls at 62/63 are written before any lower entry changes so coverage never lapses."""
        code = make_random_loader(num_regions=1, num_random=1).setup_pma()
        self.assertLess(code.index("# PMA catchall pmacfg62"), code.index("# Setting up pmacfg0 "))
        self.assertLess(code.index(f"li t0, 0x{PMA_DRAM_CATCHALL:x}"), code.index("# Invalidate pmacfg"))

    def test_randomize_catchalls_never_write_pmamask(self):
        """An explicit mireg2 write collapses whisper's 2^56 DRAM catchall to page 0; skip it."""
        code = make_random_loader(num_regions=1, num_random=1).setup_pma()
        catchall_block = code[code.index("# PMA catchall pmacfg62") : code.index("# Setting up pmacfg0 ")]
        self.assertIn("csrw mireg, t0", catchall_block)
        self.assertNotIn("mireg2", catchall_block)

    def test_indirect_pct_100_programs_low_entries_indirectly(self):
        """pct=100 routes entries 0-15 through miselect/mireg/mireg2 like the high entries."""
        code = make_random_loader(num_regions=2, num_random=2, user_programmable=4, indirect_pct=100).setup_pma()
        for i in range(4, 8):  # programmed entries are [reserved, reserved+regions)
            self.assertIn(f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + i:x}", code, f"entry {i} must use indirect access")
            self.assertNotIn(f"csrw 0x{0x7E0 + i:x},", code, f"entry {i} must not use direct pmacfg CSR")
            self.assertNotIn(f"csrw 0x{0x7F0 + i:x},", code, f"entry {i} must not use direct pmamask CSR")
        # Invalidated low entries go indirect too
        self.assertIn("# Invalidate pmacfg8 (indirect)", code)

    def test_indirect_pct_zero_keeps_low_entries_direct(self):
        """pct=0 emits only direct CSRs for entries 0-15 and never rolls the rng."""
        code = make_random_loader(num_regions=2, num_random=2, user_programmable=4, indirect_pct=0).setup_pma()
        self.assertIn("csrw 0x7e4, t0", code)
        self.assertNotIn(f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 4:x}", code)
        self.assertNotIn("# Invalidate pmacfg8 (indirect)", code)

    def test_indirect_pct_auto_matches_explicit_50_when_randomizing(self):
        """Unset pct auto-resolves to 50 under randomization: same output as explicit 50 for the same seed."""
        auto = make_random_loader(num_regions=2, num_random=2, user_programmable=4, indirect_pct=-1).setup_pma()
        explicit = make_random_loader(num_regions=2, num_random=2, user_programmable=4, indirect_pct=50).setup_pma()
        self.assertEqual(auto, explicit)


if __name__ == "__main__":
    unittest.main()
