# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

"""
Tests for the TT 64-entry PMA scheme in Loader.setup_pma():

- pmacfg0-15 written directly (0x7E0-0x7EF), each paired with a pmamask clear (0x7F0-0x7FF)
- pmacfg/pmamask 16-63 written indirectly via miselect/mireg/mireg2
- catchalls re-established at entries 62 (IO) and 63 (DRAM)
- FeatMgr.num_pmas defaults to 64

This file is private (excluded from public release via .tafconfig).
"""

import re
import unittest
from typing import Optional

from riescue.dtest_framework.config import FeatMgr
from riescue.dtest_framework.lib.pma import PmaInfo
from riescue.dtest_framework.pool import Pool
from riescue.dtest_framework.runtime import Runtime
from riescue.dtest_framework.runtime.loader import Loader, PMA_INDIRECT_SELECT_BASE, PMA_IO_CATCHALL, PMA_DRAM_CATCHALL
from riescue.lib.rand import RandNum


def make_loader(num_regions: int, num_pmas: Optional[int] = None, user_programmable: int = 0) -> Loader:
    """Build a Loader with needs_pma set and ``num_regions`` non-adjacent memory PMA regions."""
    featmgr = FeatMgr(needs_pma=True, user_programmable_pmacfg=user_programmable)
    if num_pmas is not None:
        featmgr.num_pmas = num_pmas
    pool = Pool()
    for i in range(num_regions):
        # Space regions 2 pages apart so consolidation cannot merge them
        pool.pma_regions.add_region(0x8000_0000 + i * 0x2000, 0x1000, "memory")
    runtime = Runtime(rng=RandNum(seed=42), pool=pool, featmgr=featmgr)
    loader = runtime._modules["loader"]
    assert isinstance(loader, Loader)
    return loader


def make_random_loader(num_regions: int = 2, num_random: int = 3, user_programmable: int = 0, num_pmas: Optional[int] = None, masked_indices: tuple = (), num_carveouts: int = 0) -> Loader:
    """Build a Loader with PMA randomization enabled, defined regions, carve-outs, and decoys."""
    featmgr = FeatMgr(needs_pma=True, enable_pma_randomization=True, user_programmable_pmacfg=user_programmable)
    if num_pmas is not None:
        featmgr.num_pmas = num_pmas
    pool = Pool()
    for i in range(num_regions):
        pool.pma_regions.add_region(0x8000_0000 + i * 0x2000, 0x1000, "memory")
    for j in range(num_carveouts):
        pool.pma_regions.add_entry(
            PmaInfo(
                pma_name=f"pma_carve_{j}",
                pma_address=0x9000_0000 + j * 0x2000,
                pma_size=0x1000,
                pma_memory_type="io",
                pma_read=True,
                pma_write=False,
                pma_execute=False,
                pma_amo_type="none",
                pma_routing_to="noncoherent",
                pma_valid=True,
            )
        )
    for k in range(num_random):
        pool.pma_random_regions.append(
            PmaInfo(
                pma_name=f"pma_rand_{k}",
                pma_address=0x2000_0000 + k * 0x10000,
                pma_size=0x1000,
                pma_mask=(1 << 20) if k in masked_indices else 0,
                pma_memory_type="memory",
                pma_cacheability="noncacheable",
                pma_amo_type="none",
                pma_valid=True,
                pma_randomized=True,
            )
        )
    runtime = Runtime(rng=RandNum(seed=42), pool=pool, featmgr=featmgr)
    loader = runtime._modules["loader"]
    assert isinstance(loader, Loader)
    return loader


class LoaderPmaTest(unittest.TestCase):
    """Check the assembly generated by Loader.setup_pma()."""

    def test_num_pmas_default_is_64(self):
        self.assertEqual(FeatMgr().num_pmas, 64)

    def test_non_randomize_capacity_includes_reserved_and_catchalls(self):
        """reserved + regions + catchalls must fit num_pmas; overflow raises instead of clobbering entries."""
        with self.assertRaises(ValueError):
            make_loader(3, num_pmas=16, user_programmable=15).setup_pma()
        code = make_loader(3, num_pmas=16, user_programmable=11).setup_pma()
        self.assertIn("# Setting up pmacfg13 ", code)  # regions at 11..13, catchalls at 14/15
        self.assertIn("# PMA catchall pmacfg14", code)

    def test_empty_pma_regions_generates_nothing(self):
        """No PMA regions -> no setup code, no catchall writes."""
        code = make_loader(0).setup_pma()
        self.assertEqual(code, "")

    def test_direct_entries_write_pmacfg_and_clear_pmamask(self):
        """Entries 0-15 use direct CSRs: pmacfg @ 0x7E0+i, pmamask cleared @ 0x7F0+i."""
        n = 16
        code = make_loader(n).setup_pma()
        for i in range(n):
            self.assertIn(f"csrw 0x{0x7E0 + i:x}, t0", code, f"missing pmacfg{i} write")
            self.assertIn(f"csrw 0x{0x7F0 + i:x}, x0", code, f"missing pmamask{i} clear")
        # No indirect writes except the two catchall entries
        selects = re.findall(r"li t1, (0x8[0-9a-f]+)", code)
        self.assertEqual(selects, [f"0x{PMA_INDIRECT_SELECT_BASE + 62:x}", f"0x{PMA_INDIRECT_SELECT_BASE + 63:x}"])

    def test_indirect_entries_use_miselect_mireg_mireg2(self):
        """Entries 16+ have no direct CSRs; they go through miselect/mireg/mireg2."""
        n = 20
        code = make_loader(n).setup_pma()
        for i in range(16, n):
            self.assertIn(f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + i:x}", code, f"missing miselect value for entry {i}")
        # Exactly 16 direct pmacfg writes (0x7E0-0x7EF); entries 16+ must not spill into 0x7F0+
        direct_pmacfg_writes = re.findall(r"csrw (0x7[ef][0-9a-f]), t0", code)
        self.assertEqual(direct_pmacfg_writes, [f"0x{0x7E0 + i:x}" for i in range(16)])
        # Exactly 16 direct pmamask clears (0x7F0-0x7FF)
        direct_pmamask_clears = re.findall(r"csrw (0x7f[0-9a-f]), x0", code)
        self.assertEqual(direct_pmamask_clears, [f"0x{0x7F0 + i:x}" for i in range(16)])
        # Entry 16 maps to miselect 0x8000000000000010 per spec
        self.assertIn("li t1, 0x8000000000000010", code)
        # Every indirect pmacfg write pairs a mireg write with a mireg2 clear
        self.assertEqual(len(re.findall(r"csrw miselect, t1", code)), (n - 16) + 2)  # +2 catchalls
        self.assertEqual(len(re.findall(r"csrw mireg, t0", code)), (n - 16) + 2)
        self.assertEqual(len(re.findall(r"csrw mireg2, x0", code)), (n - 16) + 2)

    def test_catchalls_at_62_and_63(self):
        """IO catchall lands on entry 62, DRAM catchall on entry 63, with pmamask cleared."""
        code = make_loader(1).setup_pma()
        io_select = f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 62:x}"
        dram_select = f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 63:x}"
        self.assertIn(io_select, code)
        self.assertIn(dram_select, code)
        self.assertIn(f"li t0, 0x{PMA_IO_CATCHALL:x}", code)
        self.assertIn(f"li t0, 0x{PMA_DRAM_CATCHALL:x}", code)
        # Catchall values match the pmacfg14/15 boot resets in whisper_config.json
        self.assertEqual(PMA_IO_CATCHALL, 0x7C00000000000007)
        self.assertEqual(PMA_DRAM_CATCHALL, 0xE0000000000001E7)
        # IO catchall (lower entry, higher priority) must be written before DRAM
        self.assertLess(code.index(io_select), code.index(dram_select))
        # mireg2 cleared for both catchall entries
        self.assertEqual(len(re.findall(r"csrw mireg2, x0", code)), 2)

    def test_select_value_bounds(self):
        """Reg 16 -> 0x8000000000000010, reg 63 -> 0x800000000000003F per spec."""
        self.assertEqual(PMA_INDIRECT_SELECT_BASE + 16, 0x8000000000000010)
        self.assertEqual(PMA_INDIRECT_SELECT_BASE + 63, 0x800000000000003F)

    def test_max_entries_accepted(self):
        """62 regions + 2 catchalls exactly fill num_pmas=64."""
        code = make_loader(62).setup_pma()
        self.assertIn("# Setting up pmacfg61 ", code)
        self.assertIn(f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 63:x}", code)

    def test_too_many_regions_raises(self):
        """Regions that leave no room for the catchalls must raise."""
        with self.assertRaises(ValueError):
            make_loader(63).setup_pma()

    def test_num_pmas_16_still_caps(self):
        """Explicit --num_pmas 16 keeps the old capacity check."""
        with self.assertRaises(ValueError):
            make_loader(17, num_pmas=16).setup_pma()

    def test_legacy_output_has_no_randomization_artifacts(self):
        """Flag off: no invalidation writes, no pmamask set values, no reserved-entry shift."""
        code = make_loader(3).setup_pma()
        self.assertNotIn("Invalidate", code)
        self.assertNotIn("Set pmamask", code)
        self.assertIn("csrw 0x7e0, t0", code, "first defined region must start at pmacfg0")


class LoaderPmaRandomizationTest(unittest.TestCase):
    """Check setup_pma() layout and emission when enable_pma_randomization is on."""

    def entry_indices(self, code: str) -> list:
        """List programmed pmacfg entry indices from the emitted comments."""
        return [int(idx) for idx in re.findall(r"# Setting up pmacfg(\d+)", code)]

    def test_reserved_entries_skipped(self):
        """user_programmable_pmacfg=4 shifts programming to pmacfg4+ and never touches [0..4)."""
        code = make_random_loader(num_regions=2, num_random=2, user_programmable=4).setup_pma()
        for i in range(4):
            self.assertNotIn(f"csrw 0x{0x7E0 + i:x},", code, f"reserved pmacfg{i} must not be written")
            self.assertNotIn(f"csrw 0x{0x7F0 + i:x},", code, f"reserved pmamask{i} must not be written")
        self.assertIn("csrw 0x7e4, t0", code, "first programmed entry must be pmacfg4")

    def test_layout_carveouts_then_decoys_then_memmap(self):
        """Emission order: carve-outs, randomized decoys, memory-map regions."""
        code = make_random_loader(num_regions=2, num_random=2, num_carveouts=1).setup_pma()
        positions = {name: code.index(name) for name in ("pma_carve_0", "pma_rand_0", "pma_rand_1")}
        memmap_pos = code.index("# Setting up pmacfg3 ")
        self.assertLess(positions["pma_carve_0"], positions["pma_rand_0"])
        self.assertLess(positions["pma_rand_1"], memmap_pos)

    def test_carveout_values_forced_nonzero(self):
        """pma_valid=True carve-outs must emit real pmacfg values (force bypasses the legacy quirk)."""
        code = make_random_loader(num_regions=0, num_random=0, num_carveouts=1).setup_pma()
        match = re.search(r"pma_carve_0[^\n]*\n\s+li t0, (0x[0-9a-f]+)", code)
        assert match is not None, "carve-out pmacfg write not found"
        self.assertNotEqual(int(match.group(1), 16), 0)

    def test_masked_decoy_emits_pmamask_after_pmacfg(self):
        """Masked decoys program pmamask with the mask value, strictly after the pmacfg write."""
        code = make_random_loader(num_regions=0, num_random=2, masked_indices=(1,)).setup_pma()
        self.assertIn("# Set pmamask1", code)
        self.assertIn(f"li t0, 0x{1 << 20:x}", code)
        self.assertIn("# Clear pmamask0", code)
        pmacfg_pos = code.index("# Setting up pmacfg1 ")
        pmamask_pos = code.index("# Set pmamask1")
        self.assertLess(pmacfg_pos, pmamask_pos)

    def test_masked_carveout_emits_pmamask(self):
        """Masked carve-outs (from the carve-out masking pass) program their pmamask like decoys."""
        loader = make_random_loader(num_regions=0, num_random=0, num_carveouts=1)
        carveout = loader.pool.pma_regions.consolidated_entries(merge_named=False)[0]
        assert carveout.pma_name == "pma_carve_0"
        carveout.pma_mask = 1 << 24
        code = loader.setup_pma()
        self.assertIn("# Set pmamask0", code)
        self.assertIn(f"li t0, 0x{1 << 24:x}", code)
        self.assertLess(code.index("# Setting up pmacfg0 "), code.index("# Set pmamask0"))

    def test_unused_entries_invalidated_up_to_62(self):
        """Entries [used, 62) are invalidated (killing boot 14/15 shadows); catchalls at 62/63 are not."""
        code = make_random_loader(num_regions=2, num_random=2, user_programmable=4).setup_pma()
        used = 4 + 2 + 2
        invalidated = sorted(int(i) for i in re.findall(r"# Invalidate pmacfg(\d+)", code))
        self.assertEqual(invalidated, list(range(used, 62)))
        # 62/63 hold the catchalls; they must be rewritten, never invalidated
        self.assertNotIn(62, invalidated)
        self.assertNotIn(63, invalidated)
        self.assertIn("# PMA catchall pmacfg62", code)
        self.assertIn("# PMA catchall pmacfg63", code)
        self.assertNotIn("# PMA catchall pmacfg14", code)

    def test_randomized_entries_below_16_direct_catchalls_indirect(self):
        """Entries below 16 use direct CSRs; catchalls go indirect at 62/63 like the legacy path."""
        code = make_random_loader(num_regions=2, num_random=2, user_programmable=8).setup_pma()
        self.assertEqual(sorted(self.entry_indices(code)), [8, 9, 10, 11])
        self.assertIn("csrw 0x7e8, t0", code)
        self.assertIn(f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 62:x}", code)
        self.assertIn(f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 63:x}", code)
        # Boot entries 14/15 are ordinary now: invalidated, never rewritten as catchalls
        self.assertIn("csrw 0x7ee, x0", code)
        self.assertNotIn("csrw 0x7ee, t0", code)

    def test_entries_spill_into_indirect(self):
        """Regions past entry 15 are programmed indirectly via miselect/mireg in randomize mode."""
        code = make_random_loader(num_regions=2, num_random=2, user_programmable=14).setup_pma()
        self.assertEqual(sorted(self.entry_indices(code)), [14, 15, 16, 17])
        self.assertIn("# Setting up pmacfg16 (indirect", code)
        self.assertIn("li t1, 0x8000000000000010", code)
        self.assertIn("li t1, 0x8000000000000011", code)

    def test_capacity_error_with_breakdown(self):
        """Overflow raises with the full breakdown in the message; decoys never count (they truncate)."""
        with self.assertRaises(ValueError) as ctx:
            make_random_loader(num_regions=16, num_random=8, user_programmable=47).setup_pma()
        self.assertIn("user_programmable=47", str(ctx.exception))
        self.assertIn("memory_map=16", str(ctx.exception))
        self.assertIn("> 64 PMA entries", str(ctx.exception))

    def test_decoys_truncated_to_budget(self):
        """Decoys beyond the 64-entry budget are dropped (with a warning), not fatal."""
        loader = make_random_loader(num_regions=2, num_random=8, user_programmable=56)
        with self.assertLogs("riescue.dtest_framework.runtime.loader", level="WARNING"):
            code = loader.setup_pma()
        # essential = 56 reserved + 2 memmap + 2 catchalls = 60 -> budget 4 decoys
        self.assertIn("pma_rand_3", code)
        self.assertNotIn("pma_rand_4", code)
        # Pool list is trimmed in step so addrgen exclusion matches what was actually programmed
        self.assertEqual(len(loader.pool.pma_random_regions), 4)

    def test_num_pmas_16_places_catchalls_at_14_15_direct(self):
        """Catchall entries derive from num_pmas: a 16-entry config uses direct CSRs at 14/15."""
        code = make_random_loader(num_regions=1, num_random=1, num_pmas=16).setup_pma()
        self.assertIn("# PMA catchall pmacfg14", code)
        self.assertIn("# PMA catchall pmacfg15", code)
        self.assertNotIn("# PMA catchall pmacfg62", code)
        self.assertIn("csrw 0x7ee, t0", code)  # direct catchall write, no miselect
        self.assertNotIn(f"li t1, 0x{PMA_INDIRECT_SELECT_BASE + 14:x}", code)
        invalidated = sorted(int(i) for i in re.findall(r"# Invalidate pmacfg(\d+)", code))
        self.assertEqual(invalidated, list(range(2, 14)))  # used=2 regions, up to catchall_base=14

    def test_user_programmable_above_capacity_raises(self):
        """Reserved entries that leave no room for regions plus catchalls must raise."""
        with self.assertRaises(ValueError):
            make_random_loader(num_regions=1, num_random=1, user_programmable=62).setup_pma()

    def test_catchalls_first_when_randomizing(self):
        """Catchalls at 62/63 are written before any lower entry changes so coverage never lapses."""
        code = make_random_loader(num_regions=1, num_random=1).setup_pma()
        self.assertLess(code.index("# PMA catchall pmacfg62"), code.index("# Setting up pmacfg0 "))
        self.assertLess(code.index(f"li t0, 0x{PMA_DRAM_CATCHALL:x}"), code.index("# Invalidate pmacfg"))

    def test_randomize_catchalls_never_write_pmamask(self):
        """An explicit mireg2 write collapses whisper's 2^56 DRAM catchall to page 0; skip it."""
        code = make_random_loader(num_regions=1, num_random=1).setup_pma()
        catchall_block = code[code.index("# PMA catchall pmacfg62") : code.index("# Setting up pmacfg0 ")]
        self.assertIn("csrw mireg, t0", catchall_block)
        self.assertNotIn("mireg2", catchall_block)


if __name__ == "__main__":
    unittest.main()
