# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

from coretp.step import (
    TestStep,
    Load,
    Store,
    HLoad,
    HXLoad,
    HStore,
    Memory,
    ModifyPte,
    Arithmetic,
    CsrRead,
    CsrWrite,
    CsrDirectAccess,
    CodePage,
    Call,
    ConditionalBlock,
    RequestPmpRegion,
    AssertEqual,
    AssertNotEqual,
    AssertException,
    AssertFetchException,
    LoadImmediateStep,
    MemAccess,
    System,
    Comment,
    Directive,
    SetWaitTimeout,
    MachineCode,
    SupervisorCode,
    UserCode,
    Label,
    ConfigureExecuteTrigger,
    ConfigureLoadTrigger,
    ConfigureStoreTrigger,
    ConfigureLoadStoreTrigger,
    ConfigureIcountTrigger,
    ConfigureItrigger,
    ConfigureEtrigger,
    EnableTrigger,
    DisableTrigger,
    SelectTrigger,
    WriteTriggerCsr,
    ReadTriggerCsr,
)
from coretp.step.memory import ReadPTE, WritePTE

from riescue.compliance.test_plan.actions import (
    Action,
    LoadAction,
    StoreAction,
    HLoadAction,
    HXLoadAction,
    HStoreAction,
    ArithmeticAction,
    MemoryAction,
    CsrReadAction,
    CsrWriteAction,
    CsrDirectAccessAction,
    ReadPteAction,
    WritePteAction,
    CodePageAction,
    CallAction,
    ModifyPteAction,
    AssertEqualAction,
    AssertNotEqualAction,
    AssertExceptionAction,
    AssertFetchExceptionAction,
    LiAction,
    MemAccessAction,
    SystemAction,
    CommentAction,
    DirectiveAction,
    ConditionalBlockAction,
    RequestPmpAction,
    SetWaitTimeoutAction,
    MachineCodeAction,
    SupervisorCodeAction,
    UserCodeAction,
    LabelTestStepAction,
    ConfigureExecuteTriggerAction,
    ConfigureLoadTriggerAction,
    ConfigureStoreTriggerAction,
    ConfigureLoadStoreTriggerAction,
    ConfigureIcountTriggerAction,
    ConfigureItriggerAction,
    ConfigureEtriggerAction,
    EnableTriggerAction,
    DisableTriggerAction,
    SelectTriggerAction,
    WriteTriggerCsrAction,
    ReadTriggerCsrAction,
)


DEFAULT_MAPPINGS: list[tuple[type[TestStep], type[Action]]] = [
    (Load, LoadAction),
    (Store, StoreAction),
    (HLoad, HLoadAction),
    (HXLoad, HXLoadAction),
    (HStore, HStoreAction),
    (Arithmetic, ArithmeticAction),
    (Memory, MemoryAction),
    (CsrRead, CsrReadAction),
    (CsrWrite, CsrWriteAction),
    (CsrDirectAccess, CsrDirectAccessAction),
    (CodePage, CodePageAction),
    (Call, CallAction),
    (AssertEqual, AssertEqualAction),
    (AssertNotEqual, AssertNotEqualAction),
    (AssertException, AssertExceptionAction),
    (AssertFetchException, AssertFetchExceptionAction),
    (LoadImmediateStep, LiAction),
    (MemAccess, MemAccessAction),
    (ModifyPte, ModifyPteAction),
    (ReadPTE, ReadPteAction),
    (WritePTE, WritePteAction),
    (System, SystemAction),
    (Comment, CommentAction),
    (Directive, DirectiveAction),
    (ConditionalBlock, ConditionalBlockAction),
    (RequestPmpRegion, RequestPmpAction),
    (SetWaitTimeout, SetWaitTimeoutAction),
    (MachineCode, MachineCodeAction),
    (SupervisorCode, SupervisorCodeAction),
    (UserCode, UserCodeAction),
    (Label, LabelTestStepAction),
    (ConfigureExecuteTrigger, ConfigureExecuteTriggerAction),
    (ConfigureLoadTrigger, ConfigureLoadTriggerAction),
    (ConfigureStoreTrigger, ConfigureStoreTriggerAction),
    (ConfigureLoadStoreTrigger, ConfigureLoadStoreTriggerAction),
    (ConfigureIcountTrigger, ConfigureIcountTriggerAction),
    (ConfigureItrigger, ConfigureItriggerAction),
    (ConfigureEtrigger, ConfigureEtriggerAction),
    (EnableTrigger, EnableTriggerAction),
    (DisableTrigger, DisableTriggerAction),
    (SelectTrigger, SelectTriggerAction),
    (WriteTriggerCsr, WriteTriggerCsrAction),
    (ReadTriggerCsr, ReadTriggerCsrAction),
]
