# SPDX-FileCopyrightText: © 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

from .arithmetic import VecVRegVRegSetup, VecVRegVRegMaskSetup, VecVRegVRegMaskExplicitSetup, VecVRegMaskVRegMaskSetup, VecWideningSetup, VecNarrowingSetup, VecIntExtensionSetup
from .floating_point import (
    VecFpConvertSetup,
    VecFPSplatSetup,
    VecFPSingleWidthSetup,
    VecFpRecSqrtSetup,
    VecFpCompareSetup,
    VecFpWideningAddSubSetup,
    VecFpSlideSetup,
    VecFpCvtBF16Setup,
    VecFpWmaBF16Setup,
)
from .load_store import (
    VecStoreUnitStrideSetup,
    VecLoadUnitStrideSetup,
    VecLoadMaskSetup,
    VecStoreMaskSetup,
    VecStoreStridedSetup,
    VecLoadStridedSetup,
    VecStoreIndexedUnorderedSetup,
    VecLoadIndexedUnorderedSetup,
    VecLoadUnitStrideFaultFirstSetup,
)
from .segmented import (
    VecStoreUnitStrideSegmentedSetup,
    VecLoadUnitStrideSegmentedSetup,
    VecLoadUnitStrideSegmentedFaultFirst,
    VecStoreStridedSegmentedSetup,
    VecLoadStridedSegmentedSetup,
    VecLoadIndexedUnorderedSegmentedSetup,
    VecStoreIndexedUnorderedSegmentedSetup,
    VecStoreWholeRegSetup,
    VecLoadWholeRegSetup,
)
from .registers import (
    VecXRegSetup,
    VecFPRegSetup,
    VecXRegDestSetup,
    VecFPRegDestSetup,
    VecVRegSetup,
    VecWholeRegMoveSetup,
    VtypeIndepVecWholeRegMoveSetup,
)
from .immediate import VecImmSetup, VecVRegImmSetup, VecVRegImmMaskSetup, VecVRegImmMaskExplicitSetup, VecVRegXRegSetup, VecVRegXRegMaskExplicitSetup, VecRegRegSetup, VecImmImmSetup, VecRegImmSetup
from .mask import OPMVV_VReg_Mask_Setup, OPMVV_Mask_Setup, OPMVV_XRegDest_VReg_Mask_Setup

__all__ = [
    "VecVRegVRegSetup",
    "VecVRegVRegMaskSetup",
    "VecVRegVRegMaskExplicitSetup",
    "VecVRegMaskVRegMaskSetup",
    "VecWideningSetup",
    "VecNarrowingSetup",
    "VecIntExtensionSetup",
    "VecFpConvertSetup",
    "VecFPSplatSetup",
    "VecFPSingleWidthSetup",
    "VecFpRecSqrtSetup",
    "VecFpCompareSetup",
    "VecFpWideningAddSubSetup",
    "VecFpSlideSetup",
    "VecFpCvtBF16Setup",
    "VecFpWmaBF16Setup",
    "VecStoreUnitStrideSetup",
    "VecLoadUnitStrideSetup",
    "VecLoadMaskSetup",
    "VecStoreMaskSetup",
    "VecStoreStridedSetup",
    "VecLoadStridedSetup",
    "VecStoreIndexedUnorderedSetup",
    "VecLoadIndexedUnorderedSetup",
    "VecLoadUnitStrideFaultFirstSetup",
    "VecStoreUnitStrideSegmentedSetup",
    "VecLoadUnitStrideSegmentedSetup",
    "VecLoadUnitStrideSegmentedFaultFirst",
    "VecStoreStridedSegmentedSetup",
    "VecLoadStridedSegmentedSetup",
    "VecLoadIndexedUnorderedSegmentedSetup",
    "VecStoreIndexedUnorderedSegmentedSetup",
    "VecStoreWholeRegSetup",
    "VecLoadWholeRegSetup",
    "VecXRegSetup",
    "VecFPRegSetup",
    "VecXRegDestSetup",
    "VecFPRegDestSetup",
    "VecVRegSetup",
    "VecWholeRegMoveSetup",
    "VtypeIndepVecWholeRegMoveSetup",
    "VecImmSetup",
    "VecVRegImmSetup",
    "VecVRegImmMaskSetup",
    "VecVRegImmMaskExplicitSetup",
    "VecVRegXRegSetup",
    "VecVRegXRegMaskExplicitSetup",
    "VecRegRegSetup",
    "VecImmImmSetup",
    "VecRegImmSetup",
    "OPMVV_VReg_Mask_Setup",
    "OPMVV_Mask_Setup",
    "OPMVV_XRegDest_VReg_Mask_Setup",
]
