name: smoke
run-name: running lint and smoke tests
on: [push]


jobs:
  check-spdx-headers:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - uses: enarx/spdx@master
      with:
        licenses: Apache-2.0

  lint:
    runs-on: ubuntu-latest
    needs: check-spdx-headers
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: python3 -m pip install wheel
      - run: python3 -m pip install -e .
      - run: flake8 . --config=.flake8
      - run: black --check .
      - run: ./docs/build.py --build_dir=public --source_dir=docs/public_source --check

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: python3 -m unittest discover -s tests/ -p "*_test.py"
      # TODO: Uncomment this when Containerfile is included
      # - run: docker build -f infra/Containerfile -t riescue-test .
      # - run: docker run riescue-test python3 -m unittest discover -s tests/ -p "*_test.py"

  deploy-docs:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'  # Only deploy from main branch
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Build docs
        run: |
          python3 -m pip install wheel
          python3 -m pip install -e .
          ./docs/build.py --build_dir=public --source_dir=docs/public_source

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy
        uses: actions/deploy-pages@v4